// Thin wrapper over Wails-generated bindings (frontend/src/wailsjs is created by `wails dev`).
import * as App from '../wailsjs/go/main/App'

export const listConnections = () => App.ListConnections()
export const saveConnection  = c => App.SaveConnection(c)
export const deleteConnection = id => App.DeleteConnection(id)
export const testConnection  = c => App.TestConnection(c)
export const connect         = id => App.Connect(id)
export const disconnect      = id => App.Disconnect(id)
export const runQuery        = (id, sql, limit, db = '') => App.RunQueryIn(id, db, sql, limit)
export const previewTable    = (id, t, limit) => App.PreviewTable(id, t, limit)
export const listDatabases   = id => App.ListDatabases(id)
export const listTables      = (id, schema) => App.ListTables(id, schema)
export const listSchemaObjects = (id, schema) => App.ListSchemaObjects(id, schema)
export const tableDetails    = (id, table) => App.TableDetails(id, table)
export const listDatabaseObjects = id => App.ListDatabaseObjects(id)
export const listSchemaColumns = (id, schema) => App.ListSchemaColumns(id, schema)
export const listColumns     = (id, t) => App.ListColumns(id, t)
export const listQueries     = id => App.ListQueries(id)
export const saveQuery       = (id, name, sql) => App.SaveQuery(id, name, sql)
export const deleteQuery     = (id, name) => App.DeleteQuery(id, name)
export const getFavorites    = id => App.GetFavorites(id)
export const toggleFavorite  = (id, t) => App.ToggleFavorite(id, t)
export const importDataGrip = () => App.ImportDataGrip()
export const applyChanges   = (id, table, changes) => App.ApplyChanges(id, table, changes)
export const stats           = () => App.Stats()
export const listHistory     = (id, limit) => App.ListHistory(id, limit)
export const clearHistory    = id => App.ClearHistory(id)
export const truncateTable   = (id, table) => App.TruncateTable(id, table)
export const tableDDL        = (id, table) => App.TableDDL(id, table)
export const exportCSV       = (id, schema, sql, name) => App.ExportCSV(id, schema, sql, name)
export const dumpDefaults    = (id, database, table) => App.DumpDefaults(id, database, table)
export const dumpPreview     = (id, options) => App.DumpPreview(id, options)
export const runDump         = (id, options) => App.RunDump(id, options)
export const pickSavePath    = (title, def) => App.PickSavePath(title, def)
export const pickFile        = title => App.PickFile(title)
export const restoreDefaults = (id, database) => App.RestoreDefaults(id, database)
export const restorePreview  = (id, options) => App.RestorePreview(id, options)
export const runRestore      = (id, options) => App.RunRestore(id, options)
export const pickOpenFile    = (title, patterns) => App.PickOpenFile(title, patterns)
export const version         = () => App.Version()
export const importJetBrains = (paths, xml) => App.ImportJetBrains(paths, xml)
export const pickDirectory   = title => App.PickDirectory(title)
export const runScript       = (id, db, sql, limit, runId) => App.RunScript(id, db, sql, limit, runId)
export const cancelQuery     = runId => App.CancelQuery(runId)
export const setTxMode       = (id, mode) => App.SetTxMode(id, mode)
export const getTxState      = id => App.GetTxState(id)
export const commit          = id => App.Commit(id)
export const rollback        = id => App.Rollback(id)
export const viewDDL         = (id, view) => App.ViewDDL(id, view)
export const routineSource   = (id, schema, name, kind) => App.RoutineSource(id, schema, name, kind)
export const tableDDLAny     = (id, table) => App.TableDDLAny(id, table)
export const exportQuery     = (id, schema, sql, format, name) => App.ExportQuery(id, schema, sql, format, name)
export const searchObjects   = (id, term, limit) => App.SearchObjects(id, term, limit)
export const getSettings     = () => App.GetSettings()
export const saveSettings    = st => App.SaveSettings(st)
export const checkUpdate     = force => App.CheckUpdate(force)
export const downloadUpdate  = kind => App.DownloadUpdate(kind)
export const installUpdate   = (kind, path) => App.InstallUpdate(kind, path)
