// Small SQL syntax highlighter for read-only previews. Colors follow the editor's One Dark theme.
const KEYWORDS = new Set(`select from where and or not in is null as insert into values update set delete create alter drop table index unique primary key foreign references constraint add modify change column rename to on after first default auto_increment comment engine collate charset character if exists cascade restrict no action generated by identity type on delete update join left right inner outer group order limit offset having distinct union all case when then else end like between truncate call begin commit rollback with recursive view trigger procedure function returns return declare using`.split(/\s+/))
const TYPES = new Set(`int integer bigint smallint tinyint mediumint decimal numeric float double real boolean bool varchar char text mediumtext longtext tinytext blob longblob date datetime timestamp timestamptz time year json jsonb uuid bytea serial bigserial unsigned enum bit binary varbinary`.split(/\s+/))
const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

export function highlightSQL(sql) {
  let out = ''
  const re = /(--[^\n]*|#[^\n]*|\/\*[\s\S]*?\*\/)|('(?:[^'\\]|\\.|'')*'|"(?:[^"\\]|\\.|"")*")|(`[^`]*`)|(\b\d+(?:\.\d+)?\b)|([A-Za-z_][A-Za-z0-9_]*)|(\S)|(\s+)/g
  let m
  while ((m = re.exec(sql))) {
    const [tok, comment, str, ident, num, word, sym, ws] = m
    if (comment) out += `<span class="h-c">${esc(tok)}</span>`
    else if (str) out += `<span class="h-s">${esc(tok)}</span>`
    else if (ident) out += `<span class="h-i">${esc(tok)}</span>`
    else if (num) out += `<span class="h-n">${esc(tok)}</span>`
    else if (word) {
      const w = word.toLowerCase()
      out += KEYWORDS.has(w) ? `<span class="h-k">${esc(tok)}</span>` : TYPES.has(w) ? `<span class="h-t">${esc(tok)}</span>` : esc(tok)
    } else out += esc(tok)
  }
  return out
}
